In [47]:
# ML model Life cycle Transformation1
import numpy as np
file=open("D:\Ravi\Ravi Data\Machine Learning\PythonClass\Venu\PatData.txt")

header=file.readline()
lines=file.readlines()
ins=[]
gender=[]
y=[]
for line in lines:
    w=line.strip().split(',')
    ins.append([float(v) for v in w[2:5]])
    gender.append(w[5])
    y.append(w[-1])
    
freq={}
for k in gender:
    if freq.get(k)==None:
        freq[k]=1
    else:
        freq[k]+=1
        
n=len(gender)
prob={}
for j in freq:
    prob[j]=freq[j]/n
new=[prob[k] for k in gender]

noise=(2*np.random.random(len(gender))-1)*0.000001
gen=new+noise

q=np.c_[gen]
X=np.concatenate((ins,q),axis=1)
Y=

In [48]:
print(freq)
print(n)
print(gender)
print(gen)
print(q)
print(X)

{'M': 4, 'F': 6}
10
['M', 'F', 'F', 'M', 'F', 'F', 'M', 'F', 'F', 'M']
[0.40000033 0.60000031 0.60000097 0.39999976 0.59999941 0.59999932
 0.40000071 0.59999963 0.60000065 0.40000006]
[[0.40000033]
 [0.60000031]
 [0.60000097]
 [0.39999976]
 [0.59999941]
 [0.59999932]
 [0.40000071]
 [0.59999963]
 [0.60000065]
 [0.40000006]]
[[25.         50.          6.          0.40000033]
 [30.         55.          5.9         0.60000031]
 [34.         60.          5.4         0.60000097]
 [40.         65.          5.6         0.39999976]
 [32.         70.          5.5         0.59999941]
 [45.         60.          5.7         0.59999932]
 [32.         54.          5.2         0.40000071]
 [50.         70.          5.6         0.59999963]
 [37.         65.          5.8         0.60000065]
 [28.         65.          5.6         0.40000006]]
